// Syncs frontend/.env → assets/env.local for Flutter runtime (Places, API URL).
// Usage: dart run tool/sync_env.dart

import 'dart:io';

const keysToSync = [
  'APP_ENV',
  'API_BASE_URL',
  'GOOGLE_MAPS_API_KEY',
  'MEATVO_API_ROOT',
  'BACKEND_ROOT_URL',
  'API_URL',
];

void main() {
  final projectRoot = Directory.current.path.endsWith('tool')
      ? Directory.current.parent
      : Directory.current;
  final envFile = File('${projectRoot.path}/.env');
  final outFile = File('${projectRoot.path}/assets/env.local');

  if (!envFile.existsSync()) {
    stderr.writeln('Missing ${envFile.path}');
    stderr.writeln('Copy .env.example → .env and set GOOGLE_MAPS_API_KEY.');
    exit(1);
  }

  final parsed = <String, String>{};
  for (final rawLine in envFile.readAsLinesSync()) {
    final line = rawLine.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    final eq = line.indexOf('=');
    if (eq <= 0) continue;
    parsed[line.substring(0, eq).trim()] = line.substring(eq + 1).trim();
  }

  final defaultsFile = File('${projectRoot.path}/assets/env.defaults');
  if (defaultsFile.existsSync()) {
    for (final rawLine in defaultsFile.readAsLinesSync()) {
      final line = rawLine.trim();
      if (line.isEmpty || line.startsWith('#')) continue;
      final eq = line.indexOf('=');
      if (eq <= 0) continue;
      final key = line.substring(0, eq).trim();
      parsed.putIfAbsent(key, () => line.substring(eq + 1).trim());
    }
  }

  final buffer = StringBuffer()
    ..writeln('# Generated by tool/sync_env.dart — do not commit (gitignored).')
    ..writeln('# Re-run after changing frontend/.env: dart run tool/sync_env.dart')
    ..writeln();

  for (final key in keysToSync) {
    final value = parsed[key];
    if (value != null && value.isNotEmpty) {
      buffer.writeln('$key=$value');
    }
  }

  if (!(parsed['GOOGLE_MAPS_API_KEY'] ?? '').isNotEmpty) {
    stderr.writeln('WARNING: GOOGLE_MAPS_API_KEY missing in .env — location search will fail.');
  }

  outFile.writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote ${outFile.path}');

  _syncGradleMapsKey(projectRoot, parsed['GOOGLE_MAPS_API_KEY'] ?? '');

  stdout.writeln('Restart the app: flutter run (full restart, not hot reload)');
}

/// Android map tiles read the key from AndroidManifest at Gradle build time.
void _syncGradleMapsKey(Directory projectRoot, String mapsKey) {
  if (mapsKey.isEmpty) {
    stderr.writeln(
      'WARNING: GOOGLE_MAPS_API_KEY not synced to android/gradle.properties',
    );
    return;
  }

  final gradleFile = File('${projectRoot.path}/android/gradle.properties');
  if (!gradleFile.existsSync()) {
    stderr.writeln('Missing ${gradleFile.path}');
    return;
  }

  final lines = gradleFile.readAsLinesSync();
  var replaced = false;
  final updated = lines.map((line) {
    if (line.trim().startsWith('GOOGLE_MAPS_API_KEY=')) {
      replaced = true;
      return 'GOOGLE_MAPS_API_KEY=$mapsKey';
    }
    return line;
  }).toList();

  if (!replaced) {
    updated.add('GOOGLE_MAPS_API_KEY=$mapsKey');
  }

  gradleFile.writeAsStringSync('${updated.join('\n')}\n');
  stdout.writeln('Updated android/gradle.properties (GOOGLE_MAPS_API_KEY)');
}
